import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { redirect, useRouter } from "next/navigation";
import { getServerSession } from "next-auth";
import { getSession, signIn, signOut, useSession } from "next-auth/react";
import { authOptions } from "@acme/auth";

import { api } from "~/utils/api";
import { Header } from "~/components/Header";
import { CreateProjectModal } from "~/modules/dashboard/CreateProjectModal";

const Home: NextPage = () => {
  const router = useRouter();
  const { data: projects } = api.project.getProjectsFromUser.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="mx-auto mt-24 flex max-w-6xl flex-col">
        <div className="flex items-center justify-between">
          <h2 className="scroll-m-20 pb-2 text-3xl font-semibold tracking-tight transition-colors first:mt-0">
            My Projects
          </h2>
          <CreateProjectModal />
        </div>
        <div className="mt-4 border-b border-b-slate-200 dark:border-b-slate-700"></div>
        <div className="mt-8 grid grid-cols-3 gap-4">
          {projects?.map((project) => (
            <Link
              href={`/project/${project.id}`}
              key={project.id}
              className="rounded-lg bg-slate-300 px-8 py-4 transition-transform ease-in hover:-translate-y-1"
            >
              <div className="">
                <h4 className="scroll-m-20 text-xl font-semibold tracking-tight">
                  {project.name}
                </h4>
                <p className="text-sm leading-7">{project.description}</p>
                <div className="mt-4">
                  <span>
                    {project.users.length} Member
                    {project.users.length > 1 ? "s" : ""}
                  </span>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </>
  );
};

export default Home;

export async function getServerSideProps(context: any) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/login",
      },
    };
  }

  return {
    props: {},
  };
}
