import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { redirect, useRouter } from "next/navigation";
import { getServerSession } from "next-auth";
import { signIn, signOut, useSession } from "next-auth/react";
import { authOptions } from "@acme/auth";

import { api } from "~/utils/api";
import { Header } from "~/components/Header";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "../ui/AlertDialog";
import { Button } from "../ui/Button";

const Home: NextPage = () => {
  const router = useRouter();
  const { status } = useSession();
  const { data: session } = api.auth.getSession.useQuery();
  const { data: projects } = api.project.getProjectsFromUser.useQuery();

  const { data: secretMessage } = api.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: !!session?.user },
  );

  if (status === "unauthenticated") {
    router.push("/api/auth/signin");
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="mx-auto mt-24 flex max-w-6xl flex-col">
        <h2 className="scroll-m-20 border-b border-b-slate-200 pb-2 text-3xl font-semibold tracking-tight transition-colors first:mt-0 dark:border-b-slate-700">
          Hello from dev branch
        </h2>
        <div className="mt-8 flex">
          {projects?.map((project) => (
            <Link href={`/project/${project.id}`} key={project.id}>
              <div className="rounded-lg bg-slate-300 px-8 py-4 transition-transform ease-in hover:-translate-y-1">
                <h4 className="scroll-m-20 text-xl font-semibold tracking-tight">
                  {project.name}
                </h4>
                <p className="text-sm leading-7">{project.description}</p>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </>
  );
};

export default Home;
